[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = "0.4"
secp256k1 = { version = "0.21", features = ["recovery"] }
tokio = { version = "1", features = ["full"] }
web3 = "0.18"
